# Autogenerated wrapper script for Channelflow_jll for aarch64-linux-gnu-cxx11
export L2op, addfields, benchmark, changegrid, continuesoln, diffop, edgetracking, extrapolatefields, fieldconvert, fieldprops, findeigenvals, findsoln, findsymmetries, optphaseshift, perturbfield, pressure, projectfield, projectseries, randomfield, simulateflow, symmetrize, symmetryop

using FFTW_jll
using HDF5_jll
using Eigen_jll
using NetCDF_jll
JLLWrappers.@generate_wrapper_header("Channelflow")
JLLWrappers.@declare_executable_product(L2op)
JLLWrappers.@declare_executable_product(addfields)
JLLWrappers.@declare_executable_product(benchmark)
JLLWrappers.@declare_executable_product(changegrid)
JLLWrappers.@declare_executable_product(continuesoln)
JLLWrappers.@declare_executable_product(diffop)
JLLWrappers.@declare_executable_product(edgetracking)
JLLWrappers.@declare_executable_product(extrapolatefields)
JLLWrappers.@declare_executable_product(fieldconvert)
JLLWrappers.@declare_executable_product(fieldprops)
JLLWrappers.@declare_executable_product(findeigenvals)
JLLWrappers.@declare_executable_product(findsoln)
JLLWrappers.@declare_executable_product(findsymmetries)
JLLWrappers.@declare_executable_product(optphaseshift)
JLLWrappers.@declare_executable_product(perturbfield)
JLLWrappers.@declare_executable_product(pressure)
JLLWrappers.@declare_executable_product(projectfield)
JLLWrappers.@declare_executable_product(projectseries)
JLLWrappers.@declare_executable_product(randomfield)
JLLWrappers.@declare_executable_product(simulateflow)
JLLWrappers.@declare_executable_product(symmetrize)
JLLWrappers.@declare_executable_product(symmetryop)
function __init__()
    JLLWrappers.@generate_init_header(FFTW_jll, HDF5_jll, Eigen_jll, NetCDF_jll)
    JLLWrappers.@init_executable_product(
        L2op,
        "bin/benchmark",
    )

    JLLWrappers.@init_executable_product(
        addfields,
        "bin/addfields",
    )

    JLLWrappers.@init_executable_product(
        benchmark,
        "bin/benchmark",
    )

    JLLWrappers.@init_executable_product(
        changegrid,
        "bin/changegrid",
    )

    JLLWrappers.@init_executable_product(
        continuesoln,
        "bin/continuesoln",
    )

    JLLWrappers.@init_executable_product(
        diffop,
        "bin/diffop",
    )

    JLLWrappers.@init_executable_product(
        edgetracking,
        "bin/edgetracking",
    )

    JLLWrappers.@init_executable_product(
        extrapolatefields,
        "bin/extrapolatefields",
    )

    JLLWrappers.@init_executable_product(
        fieldconvert,
        "bin/fieldconvert",
    )

    JLLWrappers.@init_executable_product(
        fieldprops,
        "bin/fieldprops",
    )

    JLLWrappers.@init_executable_product(
        findeigenvals,
        "bin/findeigenvals",
    )

    JLLWrappers.@init_executable_product(
        findsoln,
        "bin/findsoln",
    )

    JLLWrappers.@init_executable_product(
        findsymmetries,
        "bin/findsymmetries",
    )

    JLLWrappers.@init_executable_product(
        optphaseshift,
        "bin/optphaseshift",
    )

    JLLWrappers.@init_executable_product(
        perturbfield,
        "bin/perturbfield",
    )

    JLLWrappers.@init_executable_product(
        pressure,
        "bin/pressure",
    )

    JLLWrappers.@init_executable_product(
        projectfield,
        "bin/projectfield",
    )

    JLLWrappers.@init_executable_product(
        projectseries,
        "bin/projectseries",
    )

    JLLWrappers.@init_executable_product(
        randomfield,
        "bin/randomfield",
    )

    JLLWrappers.@init_executable_product(
        simulateflow,
        "bin/simulateflow",
    )

    JLLWrappers.@init_executable_product(
        symmetrize,
        "bin/symmetrize",
    )

    JLLWrappers.@init_executable_product(
        symmetryop,
        "bin/symmetryop",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
